
name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart run test --coverage="./coverage"
      - name: Activate coverage
        run: dart pub global activate coverage
      - name: Format coverage
        run: format_coverage -l -i ./ -o lcov.info --packages=.dart_tool/package_config.json --report-on=lib
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
